
# The font's name. Also determines the file names of generated templates.
font_name: ysdn-icons
css_selector: .i-{{glyph}}
no_hash: true
force: true
quiet: true

input:
 vectors: assets/icons/export
 templates: assets/icons/templates

output:
 fonts: assets/fonts/
 _icons.scss: assets/css/partials/

preprocessor_path: /assets/fonts/


# -----------------------------------------------------------------------------
# Templates
#   A YAML array of templates and files to generate alongside fonts. Custom
#   templates should be saved in the INPUT[:templates] directory and referenced
#   by their base file name.
#
#   For Rails and Compass templates, set `preprocessor_path` as the relative
#   path from OUTPUT[:css] to OUTPUT[:fonts]. By default, these are the same
#   directory.
#
#   Included in Font Custom: preview, css, scss, scss-rails
#   Default: css, preview
# -----------------------------------------------------------------------------

templates:
  - _icons.scss

# -----------------------------------------------------------------------------
# Font Settings (defaults shown)
# -----------------------------------------------------------------------------

# The em size. Setting this will scale the entire font to the given size.
#font_em: 512

# The font's ascent and descent. Used to calculate the baseline.
#font_ascent: 448
#font_descent: 64

# Horizontally fit glyphs to their individual vector widths.
#autowidth: false
